import { GRID_SIZE, SLOT_COSTS } from './grid';
import { ANIMATIONS } from './animations';
import { WORKER_CONFIG, MERGE_RULES, WORKER_RARITY } from './workers';
import { MINING_CONFIG, MINING_MULTIPLIER } from './mining';

export const GAME_CONFIG = {
  INITIAL_BALANCES: {
    emsx: 10,
    usdt: 0,
    btc: 0
  },
  BASE_MINING_RATES: {
    emsx: 0.1,
    usdt: 0.01,
    btc: 0.001
  },
  UPDATE_INTERVAL: MINING_CONFIG.UPDATE_INTERVAL,
  LEVEL_MULTIPLIER: MINING_CONFIG.LEVEL_MULTIPLIER,
  OFFLINE_MINING_RATE: MINING_CONFIG.OFFLINE_MINING_RATE,
  MAX_OFFLINE_TIME: MINING_CONFIG.MAX_OFFLINE_TIME,
  MAX_LEVEL: WORKER_CONFIG.MAX_LEVEL,
  WORKER_COSTS: WORKER_CONFIG.WORKER_COSTS,
  UPGRADE_COST_MULTIPLIER: WORKER_CONFIG.UPGRADE_COST_MULTIPLIER,
  SLOT_COSTS,
  GRID_SIZE,
  MERGE_RULES,
  WORKER_RARITY,
  ANIMATIONS
};

export {
  GRID_SIZE,
  SLOT_COSTS,
  MINING_CONFIG,
  MINING_MULTIPLIER,
  WORKER_CONFIG,
  MERGE_RULES,
  WORKER_RARITY,
  ANIMATIONS
};